<!DOCTYPE html><html lang="en"><head> <meta charset="utf-8"> <meta http-equiv="X-UA-Compatible" content="IE=edge"> <meta name="viewport" content="width=device-width, initial-scale=1"> <title>High Carbon Ferro Manganese Manufacturers | Bharat Engineers</title> <meta name="description" content="Bharat is premium quality High Carbon Ferro Manganese Manufacturers. This high carbon plays an active role as a deoxidizer for steel in Ferro manganese."/> <meta name="keyword" content="High Carbon Ferro Manganese Manufacturers, High Carbon Ferro Manganese, Ferro Manganese Manufacturers in India, Ferro Manganese Manufacturers, Manufacturers, Exporters, Suppliers, India"/><link rel="canonical" href="https://www.bharatengg.in/ferro-alloy/high-carbon-ferro-manganese-manufacturers.php"/> <meta name="robots" content="index,follow"/> <link href="../images/bharat/favicon.png" rel="icon"> <link href="../css/bootstrap.min.css" rel="stylesheet"> <link href="../css/style.css" rel="stylesheet"> <link href="../css/responsive-style.css" rel="stylesheet"> <link href="../css/effect_style.css" rel="stylesheet"> <link rel="stylesheet" href="../css/animate.min.css"> <link rel="stylesheet" href="../css/animate.css"> <meta name="google-site-verification" content="vkKUdWdIV-BDr-mhe4-Okc0sZGXu3u05GOQpjApC3-8"/> <!-- Global site tag (gtag.js) - Google Analytics --> <script async src="https://www.googletagmanager.com/gtag/js?id=UA-21685912-15"></script><script>window.dataLayer=window.dataLayer || []; function gtag(){dataLayer.push(arguments);}gtag('js', new Date()); gtag('config', 'UA-21685912-15');</script> <script>(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o), m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)})(window,document,'script','https://www.google-analytics.com/analytics.js','ga'); ga('create', 'UA-21685912-15', 'auto'); ga('send', 'pageview'); </script> <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src='https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);})(window,document,'script','dataLayer','GTM-5N92M4D');</script> <script async src="https://www.googletagmanager.com/gtag/js?id=AW-859902389"></script><script>window.dataLayer=window.dataLayer || []; function gtag(){dataLayer.push(arguments);}gtag('js', new Date()); gtag('config', 'AW-859902389');</script>

<script type="application/ld+json">
 {
 "@context": "https://schema.org",
 "@type": "WebPage",
 "name": "High Carbon Ferro Manganese Manufacturers | Bharat Engineers",
 "description": "Bharat is premium quality High Carbon Ferro Manganese Manufacturers. This high carbon plays an active role as a deoxidizer for steel in Ferro manganese.",
 "url": "https://www.bharatengg.in/ferro-alloy/high-carbon-ferro-manganese-manufacturers.php",
 "inLanguage": "en",
 "isPartOf": {
 "@type": "WebSite",
 "name": "Bharat Engineering Works",
 "url": "https://www.bharatengg.in"
 },
 "publisher": {
 "@type": "Organization",
 "name": "Bharat Engineering Works",
 "url": "https://www.bharatengg.in",
 "logo": {
 "@type": "ImageObject",
 "url": "https://www.bharatengg.in/images/bharat/up1501.jpg"
 }
 }
 }
 </script>




</head> <body> <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-5N92M4D" height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript><?php include_once('../headerseo.php'); ?> <div class="inner-pages-bnr"> <img src="../images/bharat/about-us-banner2.png" class="img-responsive" alt="cnc-banner-image"> <div class="banner-caption"> <h1>High Carbon Ferro Manganese Manufacturers</h1> <ul class="breadcumb"> <li><a href="../index.php">Home</a> - </li><li><a href="../product.php">Products</a> - </li><li>High Carbon Ferro Manganese Manufacturers</li></ul> </div></div><section class="pad60-top-bottom"> <div class="container-fluid"> <div class="row"> <div class="container"> <div class="col-md-12 col-sm-12 col-xs-12"> <div class="text-section"> <h3 class="seoh">High Carbon Ferro Manganese Manufacturers</h3> <div class="image-section seoimg"> <span class="image_hover sehi"> <img src="../images/bharat/Gallery/ferro/FERROMANGANESE.png" alt="High Carbon Ferro Manganese Manufacturers" title="High Carbon Ferro Manganese Manufacturers" class="imagee zoom_img_effect img-responsive sei"> </span> </div><p class="sep">Being ISO 9001 2008 certified <strong>High Carbon Ferro Manganese Manufacturers</strong>, we, the Bharat Engineering Works Pvt. Ltd produce highly efficient and cost effective high carbon Ferro Manganese. The offered Ferro Manganese is used as the oxidizer for steel in many steel manufacturing plants.</p><br/> <p class="sep">We have centralized our head office in Kolkata, India. We highly promote eco-friendly concept and hence perform the manufacturing of high carbon Ferro Manganese in almost 60% of our open land bank or dedicated greenbelt. Likewise, our skilled <strong>High Carbon Ferro Manganese Manufacturers</strong>, use solar energy instead of fossil fuel thereby reducing the carbon dioxide proportion. Besides, we strictly follow the legal and legislative laws and thus make sure to use only the required resources that too wisely, efficiently, and responsibly.</p><br/> <p class="sep">With the true experience of 4 decades, Bharat Engineering Works are manufacturing and supplying the High Carbon Ferro Manganese in India as well as export to 25 more countries all over the world. Along with the product delivery, we also facilitate our honourable customers with comprehensive customer services and sales service.</p><br/> <p class="sep"><span class="seoh4">Area Covered by Bharat Engineering Work : High Carbon Ferro Manganese Manufacturers : </span>India and 25 other countries</p><br/> <p class="sep"><span class="seoh4">Business Type of Bharat Engineering Work : High Carbon Ferro Manganese : </span>Manufacturers, Suppliers and Exporters</p></br><p class="sep"><span class="seoh4"> Other Related Products:</span> <a href= https://www.bharatengg.in/ferro-alloy/ferro-manganese-manufacturers-in-india.php> Ferro Manganese Manufacturers in India</a></p>
</div></div><div class="col-md-6 col-sm-6 col-xs-12 mt35"> <h3 class="seoapp">Applications</h3> <ul class="seo-ul"> <li class="seo-li"><i class="fa fa-arrow-right fadr"></i>Reputed PSUs</li><li class="seo-li"><i class="fa fa-arrow-right fadr"></i>Integrated Steel Plants</li><li class="seo-li"><i class="fa fa-arrow-right fadr"></i>Mini Steel Plants</li><li class="seo-li"><i class="fa fa-arrow-right fadr"></i>Rolling Mills</li><li class="seo-li"><i class="fa fa-arrow-right fadr"></i>Heavy Engineering and Equipment Manufacturers</li><li class="seo-li"><i class="fa fa-arrow-right fadr"></i>Metal Smelting Companies</li><li class="seo-li"><i class="fa fa-arrow-right fadr"></i>Shipping and Infrastructure Companies</li><li class="seo-li"><i class="fa fa-arrow-right fadr"></i>Defence</li><li class="seo-li"><i class="fa fa-arrow-right fadr"></i>Power Plants</li></ul> </div><div class="col-md-6 col-sm-6 col-xs-12 mt35"> <h3 class="seoapp">Features</h3> <ul class="seo-ul"> <li class="seo-li"><i class="fa fa-arrow-right fadr"></i>Premium Quality products</li><li class="seo-li"><i class="fa fa-arrow-right fadr"></i>Competitive prices</li><li class="seo-li"><i class="fa fa-arrow-right fadr"></i>Highly durable and reliable</li><li class="seo-li"><i class="fa fa-arrow-right fadr"></i>Causes low maintenance cost</li></ul> </div></div></div></div></section> <?php include_once('../footerseo.php'); ?> 
<script src="../js/jquery.min.js"></script> <script src="../js/bootstrap.min.js"></script> <script src="../js/custom.js"></script> <script src="../js/theme.js"></script> </body></html>
