<?php $page='request'; ?><!DOCTYPE html><html lang="en"><head> <meta charset="utf-8"> <meta http-equiv="X-UA-Compatible" content="IE=edge"> <meta name="viewport" content="width=device-width, initial-scale=1"> <link href="images/bharat/favicon.png" rel="icon"> <title>Request a Quote | Bharat Engineering - Fast Response</title>
<meta name="description" content="Request a custom quote from Bharat Engineering Works for industrial castings, ferro alloys, and engineering components. Get a prompt response from our team.">
 <link rel="canonical" href="https://www.bharatengg.in/request-quote.php"/>
<link href="css/bootstrap.min.css" rel="stylesheet"> <link href="css/style.css" rel="stylesheet"> <link href="css/responsive-style.css" rel="stylesheet"> <link href="css/effect_style.css" rel="stylesheet"> <meta name="google-site-verification" content="vkKUdWdIV-BDr-mhe4-Okc0sZGXu3u05GOQpjApC3-8"/> <!-- Global site tag (gtag.js) - Google Analytics --> <script async src="https://www.googletagmanager.com/gtag/js?id=UA-21685912-15"></script><script>window.dataLayer=window.dataLayer || []; function gtag(){dataLayer.push(arguments);}gtag('js', new Date()); gtag('config', 'UA-21685912-15');</script> <script src="https://www.google.com/recaptcha/api.js" async defer></script> <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src='https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);})(window,document,'script','dataLayer','GTM-5N92M4D');</script> <script async src="https://www.googletagmanager.com/gtag/js?id=AW-859902389"></script><script>window.dataLayer=window.dataLayer || []; function gtag(){dataLayer.push(arguments);}gtag('js', new Date()); gtag('config', 'AW-859902389');</script>


<script type="application/ld+json">
 {
  "@context": "https://schema.org",
  "@type": "ContactPage",
  "name": "Request a Quote | Bharatengg",
  "description": "Request a custom quote from Bharat Engineering Works for high-quality industrial castings, ferro alloys, and engineering components. Submit your requirements and get a prompt response from our team.",
  "url": "https://www.bharatengg.in/contact.php",
  "inLanguage": "en"
 }
 </script>

</head> <body> <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-5N92M4D" height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript><?php include_once('header.php'); ?> <div class="inner-pages-bnr"> <img src="images/requestquote-banner.jpg" class="img-responsive" alt="request-banner-image"> <div class="banner-caption"> <h1>Request A Quote</h1> <ul class="breadcumb"> <li><a href="index.php">Home</a> - </li><li>Request A Quote</li></ul> </div></div><section class="pad95-100-top-bottom"> <div class="container"> <div class="row"> <div class="col-md-8 col-sm-12 col-xs-12 faq-mobile-margin"> <div class="contact-form request-form"> <form action="https://mrcreativedemo.com/DontDelete/bharat-eng/request-mail.php" name="raqForm" method="post" enctype="multipart/form-data"> <div class="col-lg-6 col-md-6 form-field"> <input name="companyname" type="text" class="form-input" placeholder="Company Name*" required> </div><div class="col-lg-6 col-md-6 form-field"> <input name="city" type="text" class="form-input" placeholder="City*"> </div><div class="col-lg-6 col-md-6 form-field"> <input name="phone" pattern="[7-9]{1}[0-9]{9}" onkeypress="return isNumber(event)" type="text" class="form-input" placeholder="Phone*" required> </div><div class="col-lg-6 col-md-6 form-field"> <input name="email" type="email" class="form-input" placeholder="Email*" required> </div><div class="col-lg-6 col-md-6 form-field"> <input name="item" type="text" class="form-input" placeholder="Item"> </div><div class="col-lg-6 col-md-6 form-field"> <input name="quantity" type="text" class="form-input" placeholder="Quantity"> </div><div class="col-lg-12 col-md-12 form-field"> <input name="website" type="text" class="form-input" placeholder="Website"> </div><div class="col-lg-12 col-md-12 form-field"> <textarea name="message" cols="1" rows="2" class="form-comment" placeholder="Message"></textarea> </div><div class="col-md-12 col-lg-12 form-field sdf fileUpload">
     <input name="file" type="file" class="form-input sd upload uploadi"> 
     </div>
     <div class="col-md-12 col-lg-12 form-field"> 
     <div class="g-recaptcha" data-sitekey="6Lfbb6MUAAAAAMPSTizykw9E9X_fabWCu0tsyxCl"></div></div><div class="col-md-12 form-field"> <input type="submit" class="form-submit-btn" value="Request A Quote"> </div></form> </div></div><div class="col-md-4 col-sm-12 left-column pull-right"> <div class="wdt-100"> <h3 class="marbtm30">Need Support?</h3> </div><div class="contact-help"> <h4>Contact us for help?</h4> <p class="fnt-17">Contact with us through our representative or submit a business inquiry online. </p></div></div></div></div></section> <?php include_once('footer.php'); ?> <script src="js/jquery.min.js"></script> <script src="js/bootstrap.min.js"></script> <script src="js/custom.js"></script> <script src="js/theme.js"></script> <script>function isNumber(evt){evt=(evt) ? evt : window.event; var charCode=(evt.which) ? evt.which : evt.keyCode; if (charCode > 31 && (charCode < 48 || charCode > 57)){return false;}return true;}</script> <script src="js/formfields.js"></script> <script src="js/jsdelivr.jquery.min.js"></script> <script src="js/jsdelivr.jquery.validate.min.js"></script> </body></html>